package com.isrdc.utils;

import org.springframework.stereotype.Component;

@Component
public class EmailPage {

	public String wlcPage (String username,String link) {
		
		
		return "<!DOCTYPE html> \r\n"
				+ "             <html lang=\"en\"> \r\n"
				+ "            <head> \r\n"
				+ "     <meta charset=\"UTF-8\">\r\n"
				+ "     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \r\n"
				+ "     <title>Email Verification</title> \r\n"
				+ "      <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\">\r\n"
				+ "            </link>\r\n"
				+ "    </head> \r\n"
				+ "     <body> \r\n"
				+ "        <div style=\"\r\n"
				+ "max-width:600px;\r\n"
				+ "margin:auto;\r\n"
				+ "background:white;\r\n"
				+ "padding:30px;\r\n"
				+ "border-radius:10px;\r\n"
				+ "box-shadow:0 0 10px rgba(0,0,0,.1);>\r\n"
				+ "\r\n"
				+ "<h4 style=\"color:#28a745;\">Hello "+ username+"</h4> \r\n"
				+ "     <p >  </p> \r\n"
				+ "    <p >Thank you for  creating account. <br>Please verify your account To login . <br>To verify account click the button below . <br>This Verification Link will expire in 24 hours </p> \r\n"
				+ "     \r\n"
				+ "    <a href=\"" + link + "\" style=\""
				+ "background:#0d6efd;"
				+ "color:#ffffff;"
				+ "padding:14px 30px;"
				+ "text-decoration:none;"
				+ "border-radius:5px;"
				+ "display:inline-block;"
				+ "font-weight:bold;"
				+ "\">Verify Email</a>\r\n"

				+ "    <p style=\"margin-top:20px;color:#555;font-size:14px;\">"
				+ "If the verification button doesn't work, copy and paste this URL into your browser:<br>"
				+ "<a href=\"" + link + "\" style=\"color:#0d6efd;word-break:break-all;\">"
				+ link
				+ "</a></p>\r\n"

				+ "    <p style=\"color:#444;\">Regards,<br><strong>Team CodeCrafters</strong></p>\r\n"

				+ "    <p style=\"font-size:12px;color:#888;\">"
				+ "This email is automated. Please do not reply."
				+ "</p>\r\n"

				+ "    <div style=\"margin-top:20px;text-align:center;font-size:12px;color:#999;\">"
				+ "© 2026 User Management System"
				+ "</div>\r\n"

				+ "</div>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}
	
	
	public String passwordResetPage(String username,String link) {
		
		
		return "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <title>Password Reset</title>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"margin:0;padding:0;background:#f4f6f9;font-family:Arial,sans-serif;\">\r\n"
				+ "\r\n"
				+ "    <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"padding:40px 0;\">\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\">\r\n"
				+ "\r\n"
				+ "                <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "                    style=\"background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 5px 15px rgba(0,0,0,.08);\">\r\n"
				+ "\r\n"
				+ "                    <!-- Header -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td align=\"center\"\r\n"
				+ "                            style=\"background:#0d6efd;padding:25px;color:#ffffff;\">\r\n"
				+ "\r\n"
				+ "                            <h2 style=\"margin:0;\">\r\n"
				+ "                                User Management System\r\n"
				+ "                            </h2>\r\n"
				+ "\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "\r\n"
				+ "                    <!-- Body -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td style=\"padding:40px;\">\r\n"
				+ "\r\n"
				+ "                            <h2 style=\"margin-top:0;color:#333;\">\r\n"
				+ "                                Reset Your Password\r\n"
				+ "                            </h2>\r\n"
				+ "\r\n"
				+ "                            <p style=\"color:#555;font-size:16px;line-height:1.6;\">\r\n"
				+ "                                Hello "+username +",\r\n"
				                                
				+ "                            </p>\r\n"
				+ "\r\n"
				+ "                            <p style=\"color:#555;font-size:16px;line-height:1.6;\">\r\n"
				+ "                                We received a request to reset the password for your account.\r\n"
				+ "                                Click the button below to create a new password.\r\n"
				+ "                            </p>\r\n"
				+ "\r\n"
				+ "                            <div style=\"text-align:center;margin:35px 0;\">\r\n"
				
                 + "                                   <a href=\"" + link + "\" "
				+ "                                    style=\"\r\n"
				+ "                                    background:#0d6efd;\r\n"
				+ "                                    color:#ffffff;\r\n"
				+ "                                    text-decoration:none;\r\n"
				+ "                                    padding:15px 35px;\r\n"
				+ "                                    border-radius:6px;\r\n"
				+ "                                    font-size:16px;\r\n"
				+ "                                    font-weight:bold;\r\n"
				+ "                                    display:inline-block;\">\r\n"
				+ "                                    Reset Password\r\n"
				+ "                                </a>\r\n"
				+ "\r\n"
				+ "                            </div>\r\n"
				+ "\r\n"
				+ "                            <p style=\"color:#555;font-size:15px;line-height:1.6;\">\r\n"
				+ "                                For your security, this password reset link will expire in\r\n"
				+ "                                <strong>15 minutes</strong>.\r\n"
				+ "                            </p>\r\n"
				+ "\r\n"
				+ "                            <p style=\"color:#555;font-size:15px;line-height:1.6;\">\r\n"
				+ "                                If you didn't request a password reset, you can safely ignore this email.\r\n"
				+ "                                Your password will remain unchanged.\r\n"
				+ "                            </p>\r\n"
				+ "\r\n"
				+ "                            <hr style=\"border:none;border-top:1px solid #eeeeee;margin:35px 0;\">\r\n"
				+ "\r\n"
				+ "                            <p style=\"font-size:13px;color:#888;\">\r\n"
				+ "                                If the button doesn't work, copy and paste the following link into your browser:\r\n"
				+ "                            </p>\r\n"
				+ "\r\n"
				+ "<p style=\"word-break:break-all;font-size:13px;color:#0d6efd;\">"
				   + link
				+ "</p>"
				+ "\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "\r\n"
				+ "                    <!-- Footer -->\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td align=\"center\"\r\n"
				+ "                            style=\"background:#f8f9fa;padding:20px;font-size:13px;color:#777;\">\r\n"
				+ "\r\n"
				+ "                            © 2026 User Management System\r\n"
				+ "\r\n"
				+ "                            <br><br>\r\n"
				+ "\r\n"
				+ "                            This is an automated email. Please do not reply to this message.\r\n"
				+ "\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "\r\n"
				+ "                </table>\r\n"
				+ "\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </table>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}

}
