spring.application.name=backend
server.port=9090
#database
spring.datasource.url=jdbc:mysql://localhost:3306/umsdb
spring.datasource.username=${database_username}
spring.datasource.password=${database_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#phone OTP
twilio.account.sid=${Auth_SID}
twilio.auth.token=${Auth_Token}
twilio.phone.number=${Twiliophone}

#email sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GmailID}
spring.mail.password=${GmailAppPassword}
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enabled=true